Review/Cleanup of master for release prep (#1147)
* :wrench: update for case where expected metadata for given package does not contain 'releases'

* :penicl: add warning for case where expected `package_version` is not found.

* :wrench: change pipenv req to version greater than previously reported problem version.

* 🙈 Add `Pipfile.lock` to `.gitignore` (When supporting multiple versions of python with pipenv don't include the lock file.

* :wrench: fix pipenv version restriction.

* :art: run black on `core.py`

* :art: fix flake8, run black

* :wrench: adjust caching (requirements.txt no longer used.

* :bug: fix Pipfile typo

* :fire: The python3.6 runtime is deprecated by aws (July 18, 2022 [phase-1], Aug 17, 2022 [phase-2]) remove from tests for next release candidate

* :art: run black
:wrench: update black check command.

* :art: run isort

* :pencil: change version 0.54.1 -> 0.55.1
:fire: remove 3.6 from SUPPORTED_VERSIONS

* :fire: remove 3.6 support

* 🔀 merge with `0.54.2-release` branch to apply 3.9 support documentation updates.
:fire: remove 3.6 support from README

* 🔀 merge with `0.54.2-release` branch to apply 3.9 support documentation updates.

* ⏪️revert __version__ back to available pypi version

Without a pypi available release the `test_slim_handler` testcase fails.

```
ERROR: No matching distribution found for zappa==0.55.1
E...................
======================================================================
ERROR: test_slim_handler (tests.tests.TestZappa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Zappa/Zappa/tests/tests.py", line 2211, in test_slim_handler
    zappa_cli.create_package()
  File "/home/runner/work/Zappa/Zappa/zappa/cli.py", line 2430, in create_package
    venv=self.zappa.create_handler_venv(),
  File "/home/runner/work/Zappa/Zappa/zappa/core.py", line 494, in create_handler_venv
    raise EnvironmentError("Pypi lookup failed")
OSError: Pypi lookup failed
-------------------- >> begin captured stdout << ---------------------
```

* :pencil: update CHANGELOG with committed changes since last release (5b6e241)

* :fire: remove 3.6 from docs

* :wrench: address review comments

* :sparkles: change release to 0.55.1

* :recycle: Update to allow specification of the latest pypi version for `test_slim_handler()`

* :white_check_mark: update `test_slim_handler()` so that lastest pypi version is *not* hardcoded (get from "git tags" result)

* :art: run black/isort

* :wrench: attempt to update github action to retrieve the latest tags.

* :wrench: fix bad ci command definition

* :pencil: created and added issue for python3.6 support removal.

* :sparkles: add `python_requires` to setup().

* :pencil: fix issue #900

* :pencil: add link to https://slackautoinviter.herokuapp.com to join slack. (the zappateam.slack may be private?)

* :fire: remove `future` (past) requirements basestring usage, replacing with isinstance(x, str)
:wrench: change usage of utcnow() -> datetime.datetime.now(datetime.timezone.utc)

* :fire: Remove 'futures' package requirement (#826)

* :pencil: fix issue #900

* :fire: remove unnecessary __future__ import
:wrench: Start versioning at 0; 0.55.1 -> 0.55.0

* :art: fix flake8

* :bug: fix cd.yaml to only run on push of tag meeting the release tag criteria. (#1152)

* :pencil: add 1152 to CHANGELOG